service: api
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.12
  region: eu-west-3

functions:
  api:
    handler: apiculture.api.app_handler
    events:
      - httpApi: '*'

plugins:
  - serverless-python-requirements
